### ISSUE TITLE
Docker build - building wheels for CB requires 800 sec

### ISSUE THREAD

**Issue by TheUnableDeveloper** [couchbase/couchbase-python-client#56]
Hello,
I'm experiencing a really slow building time on building this library on docker.

I have two micro-services based on this library, one of them requires 800 seconds to build only the wheel for couchbase
(it displays this: `Building wheel for couchbase (pyproject.toml): still running...` for the whole 800 sec)
and the other one builds the entire image in less then 1 or 2 minutes.

Considering that the CB client versions are different from project to project, I tried to use the same at some point, but I didn't see any improvements.

Can I ask which packages/libraries should I install, or best practice to follow, to make it faster?
Because the second base image (nvidia one) is too big to understand which are the useful differences.

I tried to install it locally on my Mac, with a venv, and it took just few seconds.
I'm running the build with `--platform linux/amd64` flag

Slow build: 1500 seconds
base image: python:3.12.5
requirements.txt:
```
couchbase===4.3.0
pandas===1.5.2
sqlalchemy===1.4.39
mysql-connector-python===9.0.0
psycopg2-binary===2.9.9
python-dotenv===1.0.1
joblib===1.4.2
azure-storage-blob===12.22.0
numpy==1.26.4
```

Faster build: 120 seconds
base image: nvcr.io/nvidia/tensorflow:22.12-tf2-py3
requirements.txt:

```
couchbase==4.1.2
pandas==1.5.2
pika==1.3.1
scikit-learn==1.2.2
pillow-simd==9.0.0.post1
fastapi==0.87.0
uvicorn[standard]==0.19.0
tqdm==4.65.0
mysql-connector-python==8.1.0
scikit-learn-intelex==2023.1.1
sqlalchemy==1.4.39
```

Thank you a lot in advance!

**Comment by thejcfactor** [comment]
Hi @TheUnableDeveloper -- We strive to provide wheels for most OSes on the versions of Python that we support.  We were late to adding support for Python 3.12 (added in v4.3.2), so that might be a reason why the install process was taking so long.  If you are able to pick up a wheel, there should be no time spent building the client.  I have provided some links below to our docs on the SDKs compatibility.

[Python Version Compatibility](https://docs.couchbase.com/python-sdk/current/project-docs/compatibility.html#python-version-compatibility) 
[OS Compatibility](https://docs.couchbase.com/python-sdk/current/project-docs/compatibility.html#os-compatibility)

I should note that we should have Python 3.13 wheels in the near future (tracked in our JIRA system: [PYCBC-1613](https://jira.issues.couchbase.com/browse/PYCBC-1613)).  Unfortunately there have been a decent amount of changes in Python's C-API that mean we need to tweak our C/C++ bindings and that causes a bit of delay for adding new wheels (small team, sprint planning, etc. 😅).

Please let me know if I can provide further information/guidance.

**Comment by TheUnableDeveloper** [comment]
Hello!
thank you for your answer.
Now I can understand, thank you!

I thought i was doing something wrong in the process.

If I understand properly the doc:
If I decide to use Python 3.12, I should use couchbase SDK 4.3.2 to take advantage of the wheel?
And, another example, Python 3.11 should use sdk 4.1.6?

Thank you!
I will do some tests in the meantime and I update you asap

**Comment by TheUnableDeveloper** [comment]
Ok, did some tests:

Base image: `python:3.11-slim`

```
couchbase===4.1.6
pandas===1.5.2
sqlalchemy===1.4.39
mysql-connector-python===9.0.0
psycopg2-binary===2.9.9
python-dotenv===1.0.1
joblib===1.4.2
azure-storage-blob===12.23.1
numpy===2.1.2
```

Successful Build in less than 2 min.

Thank you!
Problem solved

**Comment by thejcfactor** [comment]
Hi @TheUnableDeveloper -- Happy to help!
